name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfribidi-dev libharfbuzz-dev libfreetype6-dev libpng-dev libfontconfig1-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::covr
            any::remotes
          needs: check

      - name: Detect package layout
        id: detect
        run: |
          if [ -f DESCRIPTION ] && [ -d R ]; then
            echo "is_pkg=true" >> $GITHUB_OUTPUT
          else
            echo "is_pkg=false" >> $GITHUB_OUTPUT
          fi

      - name: Run R CMD check (package)
        if: steps.detect.outputs.is_pkg == 'true'
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual','--as-cran'), error_on = 'warning')"

      - name: Run tests (script project)
        if: steps.detect.outputs.is_pkg == 'false'
        run: Rscript tests/run_tests.R

      - name: Upload check results on failure
        if: failure() && steps.detect.outputs.is_pkg == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: rcmdcheck-results
          path: check

      - name: Coverage (package)
        if: steps.detect.outputs.is_pkg == 'true'
        run: Rscript -e 'if (requireNamespace("covr", quietly = TRUE)) covr::codecov()'
