name: Run Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Install minimal dependencies
        run: |
          Rscript -e 'install.packages(c("testthat","ggplot2","matrixStats"), repos = "https://cloud.r-project.org")'

      - name: Run testthat tests
        run: Rscript tests/run_tests.R

